In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


In [2]:
## Intro to tensors
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
#Vector
vector = torch.tensor([1,2,3,4])
vector

tensor([1, 2, 3, 4])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([4])

In [8]:
#Matrix
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX


tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1,2]

tensor(6)

In [11]:
MATRIX.shape


torch.Size([2, 3])

In [13]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])